- name: Configuring Apache Web Server on RedHat EC2 Instance
  hosts: all
  become: true
  tasks:
    - name: Installing HTTPD Package
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Starting and Enabling HTTPD
      ansible.builtin.systemd:
        name: httpd
        state: started
        enabled: true

    - name: Creating index.html with content
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: "Hello from the EC2 Instance\n"
        owner: root
        group: root
        mode: '0644'

    # - name: Ensure firewalld is installed
    #   ansible.builtin.yum:
    #     name: firewalld
    #     state: present

    # - name: Ensure firewalld is running and enabled
    #   ansible.builtin.systemd_service:
    #     name: firewalld
    #     state: started
    #     enabled: true

    # - name: Enabling traffic on HTTP (port 80)
    #   ansible.posix.firewalld:
    #     service: http
    #     permanent: true
    #     state: enabled
    #     immediate: true