- name: Configuring Apache Web Server on RedHat EC2 Instance
  hosts: all
  become: true
  tasks:
    - name: Installing HTTPD Package
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Starting and Enabling HTTPD
      ansible.builtin.systemd:
        name: httpd
        state: started
        enabled: true

    - name: Creating index.html with content
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: "Hello from the EC2 Instance\n"
        owner: root
        group: root
        mode: '0644'